// utils/quotes.ts

export const motivationalQuotes: string[] = [
    "Acredite em você mesmo e tudo será possível.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "A persistência realiza o impossível.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "Comece onde você está. Use o que você tem. Faça o que você pode.",
    "Não espere por oportunidades, crie-as.",
    "A jornada de mil milhas começa com um único passo.",
    "Você é mais forte do que imagina.",
    "Seja a mudança que você quer ver no mundo.",
    "A falha é apenas a oportunidade de recomeçar com mais inteligência.",
    "Acredite que você pode, e você já está no meio do caminho.",
    "O futuro pertence àqueles que acreditam na beleza de seus sonhos.",
    "A disciplina é a ponte entre metas e realizações.",
    "A melhor maneira de prever o futuro é criá-lo.",
    "O otimismo é a fé que leva à realização.",
    "Quanto maior o obstáculo, maior a glória em superá-lo.",
    "Nunca é tarde demais para ser o que você poderia ter sido.",
    "A vida é 10% o que acontece comigo e 90% como eu reajo a isso.",
    "Transforme suas feridas em sabedoria.",
    "A felicidade não é algo pronto. Ela vem de suas próprias ações.",
    "Acreditar é a força que nos permite subir os maiores degraus da vida.",
    "Cada novo dia é uma nova chance para mudar sua vida.",
    "Não tenha medo de desistir do bom para perseguir o ótimo.",
    "O segredo para progredir é começar.",
    "O que você faz hoje pode melhorar todos os seus amanhãs.",
    "A coragem não é a ausência do medo, mas o triunfo sobre ele.",
    "Você não pode mudar seu futuro, mas pode mudar seus hábitos.",
    "O entusiasmo move o mundo.",
    "A vida encolhe ou expande em proporção à sua coragem.",
    "Aprenda com o ontem, viva para o hoje, espere pelo amanhã.",
    "O único limite para nossa realização de amanhã serão nossas dúvidas de hoje.",
    "A excelência não é um ato, mas um hábito.",
    "Sonhe grande e ouse falhar.",
    "Nossa maior fraqueza está em desistir.",
    "A força não vem da capacidade física, mas de uma vontade indomável.",
    "Aja como se o que você faz fizesse a diferença. E faz.",
    "Defina metas que te façam pular da cama de manhã.",
    "Pequenos começos podem levar a grandes resultados.",
    "Mire na lua. Mesmo que erre, você pousará entre as estrelas.",
    "Um dia de cada vez.",
    "A determinação de hoje é o sucesso de amanhã.",
    "Sua atitude determina sua direção.",
    "Seja a energia que você quer atrair.",
    "Não conte os dias, faça os dias contarem.",
    "Acredite no poder dos seus sonhos.",
    "A sorte favorece os corajosos.",
    "O esforço de hoje constrói o amanhã.",
    "A paciência é uma virtude.",
    "Continue em frente, o caminho se abre.",
    "Seja grato pelo que você tem.",
    "A simplicidade é a sofisticação máxima.",
    "Foque no progresso, não na perfeição.",
    "A criatividade é a inteligência se divertindo.",
    "O impossível é apenas uma opinião.",
    "Você é o autor da sua própria história.",
    "Seja a sua própria inspiração.",
    "Nunca subestime o poder de um pequeno passo.",
    "A mudança começa na sua mente.",
    "Abrace a jornada, confie no processo.",
    "Tudo o que você precisa já está dentro de você.",
    "A vida começa no final da sua zona de conforto.",
    "Faça mais do que te faz feliz.",
    "Seja mais forte que suas desculpas.",
    "Um objetivo sem um plano é apenas um desejo.",
    "O sucesso não é final, o fracasso não é fatal: é a coragem de continuar que conta.",
    "Acredite nos seus instintos.",
    "Seja a voz, não o eco.",
    "O trabalho duro vence o talento quando o talento não trabalha duro.",
    "A única coisa que fica entre você e seu sonho é a vontade de tentar.",
    "A melhor vingança é um sucesso maciço.",
    "Se você quer voar, desista de tudo que te pesa.",
    "A vida é sobre criar a si mesmo.",
    "Não é sobre ter tempo, é sobre fazer tempo.",
    "Cada dia é uma segunda chance.",
    "Aja com o coração.",
    "Seja gentil, sempre.",
    "A mente é tudo. O que você pensa, você se torna.",
    "Aprecie as pequenas coisas.",
    "A consistência é a chave.",
    "O que não te desafia, não te muda.",
    "Grandes coisas nunca vêm de zonas de conforto.",
    "Seja corajoso o suficiente para ser ruim em algo novo.",
    "Vá onde você se sente mais vivo.",
    "Continue crescendo, continue brilhando.",
    "O progresso lento ainda é progresso.",
    "Dê o seu melhor, sempre.",
    "Acredite na sua magia.",
    "A jornada é a recompensa.",
    "A dúvida mata mais sonhos do que o fracasso jamais matará.",
    "Seja o herói da sua própria história.",
    "O seu foco determina a sua realidade.",
    "Crie o seu próprio sol.",
    "A vida é curta, faça valer a pena.",
    "Aprenda algo novo todos os dias.",
    "Respire fundo, é só um dia ruim, não uma vida ruim.",
    "O segredo da felicidade é a liberdade.",
    "A gratidão transforma o que temos em suficiente.",
    "O sucesso é construído sobre a coragem de começar.",
    "Seja a razão do sorriso de alguém hoje.",
    "Não pare até se orgulhar.",
    "A beleza começa no momento em que você decide ser você mesmo.",
    "Seja a melhor versão de si mesmo.",
    "Confie no tempo da sua vida.",
    "As estrelas não podem brilhar sem a escuridão.",
    "Faça acontecer.",
    "Sonhe, acredite, conquiste.",
    "Nunca desista de algo que você não consegue passar um dia sem pensar.",
    "O obstáculo é o caminho.",
    "A felicidade é uma jornada, não um destino.",
    "Seja positivo, paciente e persistente.",
    "Comece a fazer.",
    "O que é para ser, será.",
    "A simplicidade é a chave para a felicidade.",
    "Seja a luz.",
    "As melhores coisas da vida não são coisas.",
    "Acredite no impossível.",
    "A vida é uma aventura, ouse.",
    "Siga seu coração.",
    "Aprenda, cresça, evolua.",
    "Um passo de cada vez.",
    "A felicidade é feita em casa.",
    "Viva, ria, ame.",
    "Faça hoje valer a pena lembrar.",
    "A paz começa com um sorriso.",
    "Seja destemido na busca do que incendeia sua alma.",
    "O poder está em você.",
    "Cresça através do que você passa.",
    "A vida é agora.",
    "Deixe sua fé ser maior que seu medo.",
    "A atitude é uma pequena coisa que faz uma grande diferença.",
    "Faça o bem e o bem virá a você.",
    "Siga em frente com confiança na direção dos seus sonhos.",
    "A felicidade é um estado de espírito.",
    "O que você planta agora, você colherá mais tarde.",
    "Continue sonhando.",
    "O seu melhor ainda está por vir.",
    "Seja um guerreiro, não um preocupado.",
    "A vida é um eco, o que você envia, volta.",
    "Seja a mudança.",
    "A mágica está em você.",
    "Abrace suas imperfeições.",
    "A vida é feita de momentos.",
    "Seja a razão, não a desculpa.",
    "Não olhe para trás, você não está indo para lá.",
    "Sua energia apresenta você antes mesmo de você falar.",
    "O momento é agora.",
    "Acredite, comece, torne-se.",
    "Seja grato, seja feliz.",
    "O sucesso é um estado de espírito.",
    "O seu potencial é infinito.",
    "Continue, vai valer a pena.",
    "Seja humilde, seja faminto.",
    "Abrace a incerteza.",
    "Seja o tipo de pessoa que você quer conhecer.",
    "A vida é simples, mas nós insistimos em complicá-la.",
    "Aja com propósito.",
    "Seja autêntico.",
    "O sucesso é doce, mas o segredo é o suor.",
    "Faça da sua vida uma obra de arte.",
    "Aja agora, pense depois.",
    "Seja um raio de sol em um dia nublado.",
    "A vida é sobre o equilíbrio.",
    "O sucesso começa com um sonho.",
    "Seja a sua prioridade.",
    "Não espere, crie.",
    "Seja a inspiração.",
    "A gratidão é a melhor atitude.",
    "A jornada importa mais que o destino.",
    "O que te move?",
    "A vida é uma tela, pinte-a com cores vivas.",
    "Seja o mestre do seu destino.",
    "Acredite na bondade.",
    "A felicidade é contagiosa.",
    "O conhecimento é poder.",
    "Seja a calmaria na tempestade.",
    "O amor é a resposta.",
    "A vida é para ser vivida.",
    "Acredite no seu valor.",
    "Seja presente.",
    "A simplicidade é bela.",
    "A vida é um presente, aproveite-o.",
    "Seja a diferença.",
    "O impossível não existe.",
    "Acredite no amanhã.",
    "Seja o seu próprio sol.",
    "A felicidade está nas pequenas coisas.",
    "A vida é o que você faz dela.",
    "Acredite na sua força.",
    "Seja a sua paz.",
    "A esperança é o sonho de quem está acordado.",
    "A vida é uma dádiva, abra-a.",
    "Acredite em milagres.",
    "Seja a sua própria luz.",
    "A felicidade é um caminho, não um fim.",
    "A vida é uma canção, cante-a.",
    "Acredite em si.",
    "Seja o amor.",
    "A gratidão abre portas.",
    "A vida é uma dança, dance-a.",
    "Acredite no processo.",
    "Seja a alegria.",
    "A fé move montanhas.",
    "A vida é um jogo, jogue-o.",
    "Acredite na jornada.",
    "Seja a calma.",
    "A gentileza é gratuita.",
    "A vida é um desafio, enfrente-o.",
    "Acredite na beleza.",
    "Seja a esperança.",
    "O sorriso é o melhor acessório.",
    "A vida é uma oportunidade, aproveite-a.",
    "Acredite na mudança.",
    "Seja a força.",
    "A positividade é uma escolha.",
    "A vida é uma promessa, cumpra-a.",
    "Acredite na sua intuição.",
    "Seja a inspiração para os outros.",
    "A felicidade é um hábito.",
    "A vida é um quebra-cabeça, resolva-o.",
    "Acredite no seu potencial.",
    "Seja a bondade.",
    "A persistência vence.",
    "A vida é uma aventura, viva-a.",
    "Acredite na sua paixão.",
    "Seja a gratidão.",
    "O sucesso é uma jornada.",
    "A vida é uma viagem, aproveite o passeio.",
    "Acredite no seu propósito.",
    "Seja a coragem.",
    "A mente é um jardim, cultive boas sementes.",
    "A vida é uma escola, aprenda.",
    "Acredite na sua visão.",
    "Seja a determinação.",
    "O fracasso é um degrau para o sucesso.",
    "A vida é um mistério, desvende-o.",
    "Acredite na sua voz.",
    "Seja a resiliência.",
    "A ação é a chave para o sucesso.",
    "A vida é um sonho, realize-o.",
    "Acredite no seu caminho.",
    "Seja a sabedoria.",
    "A humildade é uma virtude.",
    "A vida é um poema, escreva-o.",
    "Acredite na sua história.",
    "Seja a honestidade.",
    "A imaginação é o começo da criação.",
    "A vida é uma melodia, componha-a.",
    "Acredite na sua arte.",
    "Seja a criatividade.",
    "O respeito é fundamental.",
    "A vida é uma pintura, pinte-a.",
    "Acredite na sua singularidade.",
    "Seja a autenticidade.",
    "A compaixão cura.",
    "A vida é uma escultura, esculpa-a.",
    "Acredite no seu talento.",
    "Seja a originalidade.",
    "A empatia conecta.",
    "A vida é uma peça, represente-a.",
    "Acredite no seu brilho.",
    "Seja a sua estrela.",
    "A união faz a força.",
    "A vida é um palco, atue.",
    "Acredite no seu futuro.",
    "Seja o protagonista.",
    "A colaboração gera resultados.",
    "A vida é uma festa, celebre-a.",
    "Acredite no seu crescimento.",
    "Seja a evolução.",
    "A inovação transforma.",
    "A vida é uma celebração, participe.",
    "Acredite na sua transformação.",
    "Seja a renovação.",
    "A curiosidade move o mundo.",
    "A vida é uma descoberta, explore-a.",
    "Acredite na sua curiosidade.",
    "Seja o explorador.",
    "A sabedoria vem da experiência.",
    "A vida é uma lição, aprenda-a.",
    "Acredite na sua experiência.",
    "Seja o aprendiz.",
    "A simplicidade é elegante.",
    "A vida é uma bênção, agradeça.",
    "Acredite nas suas bênçãos.",
    "Seja a gratidão em pessoa.",
    "A alegria está no agora.",
    "A vida é o momento, viva-o.",
    "Acredite no presente.",
    "Seja o agora.",
    "A beleza está nos olhos de quem vê.",
    "A vida é bela, admire-a.",
    "Acredite na beleza interior.",
    "Seja a beleza.",
    "A paz interior é o maior tesouro.",
    "A vida é paz, encontre-a.",
    "Acredite na sua paz.",
    "Seja a paz que você busca.",
    "O amor próprio é o começo de tudo.",
    "A vida é amor, ame-se.",
    "Acredite no seu amor próprio.",
    "Seja o seu maior amor.",
    "A saúde é a maior riqueza.",
    "A vida é saúde, cuide-se.",
    "Acredite na sua saúde.",
    "Seja o seu bem-estar.",
    "A família é a base de tudo.",
    "A vida é família, valorize-a.",
    "Acredite na sua família.",
    "Seja o alicerce.",
    "A amizade é um tesouro.",
    "A vida é amizade, cultive-a.",
    "Acredite nos seus amigos.",
    "Seja o bom amigo.",
    "O trabalho dignifica.",
    "A vida é trabalho, dedique-se.",
    "Acredite no seu trabalho.",
    "Seja o profissional.",
    "O descanso é essencial.",
    "A vida é descanso, aproveite.",
    "Acredite no seu descanso.",
    "Seja o equilíbrio.",
    "O lazer é necessário.",
    "A vida é lazer, divirta-se.",
    "Acredite no seu lazer.",
    "Seja a diversão.",
    "A natureza inspira.",
    "A vida é natureza, conecte-se.",
    "Acredite na natureza.",
    "Seja a conexão.",
    "A arte alimenta a alma.",
    "A vida é arte, aprecie-a.",
    "Acredite na arte.",
    "Seja o apreciador.",
    "A música acalma o coração.",
    "A vida é música, ouça-a.",
    "Acredite na música.",
    "Seja a melodia.",
    "A leitura expande a mente.",
    "A vida é leitura, leia.",
    "Acredite nos livros.",
    "Seja o leitor.",
    "A viagem enriquece a alma.",
    "A vida é viagem, viaje.",
    "Acredite nas viagens.",
    "Seja o viajante.",
    "A comida une as pessoas.",
    "A vida é comida, saboreie.",
    "Acredite na boa comida.",
    "Seja o gourmet.",
    "O esporte fortalece o corpo e a mente.",
    "A vida é esporte, pratique.",
    "Acredite no esporte.",
    "Seja o atleta.",
    "O voluntariado enobrece.",
    "A vida é voluntariado, ajude.",
    "Acredite no voluntariado.",
    "Seja o voluntário.",
    "A educação transforma o mundo.",
    "A vida é educação, estude.",
    "Acredite na educação.",
    "Seja o estudante.",
    "A tecnologia conecta o mundo.",
    "A vida é tecnologia, use-a com sabedoria.",
    "Acredite na tecnologia.",
    "Seja o inovador.",
    "A história nos ensina.",
    "A vida é história, aprenda com ela.",
    "Acredite na história.",
    "Seja o historiador.",
    "O futuro é promissor.",
    "A vida é futuro, construa-o.",
    "Acredite no futuro.",
    "Seja o construtor.",
    "O passado nos molda.",
    "A vida é passado, aceite-o.",
    "Acredite no seu passado.",
    "Seja a sua história.",
    "O presente é uma dádiva.",
    "A vida é presente, viva-o intensamente.",
    "Acredite no agora.",
    "Seja o momento.",
    "A espiritualidade nos guia.",
    "A vida é espiritualidade, encontre a sua.",
    "Acredite na sua espiritualidade.",
    "Seja a sua fé.",
    "A meditação acalma a mente.",
    "A vida é meditação, pratique.",
    "Acredite na meditação.",
    "Seja a paz interior.",
    "A yoga equilibra o corpo e a alma.",
    "A vida é yoga, pratique.",
    "Acredite na yoga.",
    "Seja o equilíbrio em movimento.",
    "A dança liberta a alma.",
    "A vida é dança, dance sem parar.",
    "Acredite na dança.",
    "Seja o movimento.",
    "O teatro nos transforma.",
    "A vida é teatro, atue no seu papel.",
    "Acredite no teatro.",
    "Seja o ator principal.",
    "O cinema nos inspira.",
    "A vida é cinema, assista aos melhores filmes.",
    "Acredite no cinema.",
    "Seja o diretor da sua vida.",
    "A fotografia eterniza momentos.",
    "A vida é fotografia, capture os melhores momentos.",
    "Acredite na fotografia.",
    "Seja o fotógrafo.",
    "A moda expressa quem somos.",
    "A vida é moda, vista-se de si mesmo.",
    "Acredite na sua moda.",
    "Seja o seu estilo.",
    "A arquitetura constrói sonhos.",
    "A vida é arquitetura, construa a sua.",
    "Acredite na sua arquitetura.",
    "Seja o arquiteto da sua vida.",
    "O design melhora o mundo.",
    "A vida é design, desenhe a sua.",
    "Acredite no seu design.",
    "Seja o designer da sua vida.",
    "A ciência busca a verdade.",
    "A vida é ciência, questione.",
    "Acredite na ciência.",
    "Seja o cientista.",
    "A matemática é a linguagem do universo.",
    "A vida é matemática, calcule os seus passos.",
    "Acredite na matemática.",
    "Seja a solução.",
    "A filosofia nos faz pensar.",
    "A vida é filosofia, reflita.",
    "Acredite na filosofia.",
    "Seja o pensador.",
    "A psicologia nos ajuda a entender.",
    "A vida é psicologia, compreenda-se.",
    "Acredite na psicologia.",
    "Seja o autoconhecimento.",
    "A sociologia nos mostra a sociedade.",
    "A vida é sociologia, interaja.",
    "Acredite na sociologia.",
    "Seja a interação.",
    "A antropologia nos revela a cultura.",
    "A vida é antropologia, descubra.",
    "Acredite na antropologia.",
    "Seja a cultura.",
    "A economia nos ensina a administrar.",
    "A vida é economia, planeje.",
    "Acredite na economia.",
    "Seja o planejador.",
    "A política organiza a sociedade.",
    "A vida é política, participe.",
    "Acredite na política.",
    "Seja o cidadão.",
    "O direito busca a justiça.",
    "A vida é direito, seja justo.",
    "Acredite no direito.",
    "Seja a justiça.",
    "A medicina cuida da saúde.",
    "A vida é medicina, cuide-se bem.",
    "Acredite na medicina.",
    "Seja a sua própria cura.",
    "A engenharia constrói o futuro.",
    "A vida é engenharia, construa seus sonhos.",
    "Acredite na engenharia.",
    "Seja o engenheiro da sua vida.",
    "A agronomia alimenta o mundo.",
    "A vida é agronomia, cultive o bem.",
    "Acredite na agronomia.",
    "Seja o semeador.",
    "A zootecnia cuida dos animais.",
    "A vida é zootecnia, ame os animais.",
    "Acredite na zootecnia.",
    "Seja o protetor.",
    "A ecologia preserva o planeta.",
    "A vida é ecologia, seja sustentável.",
    "Acredite na ecologia.",
    "Seja a sustentabilidade.",
    "A geologia estuda a Terra.",
    "A vida é geologia, conheça o seu terreno.",
    "Acredite na geologia.",
    "Seja a rocha.",
    "A geografia descreve o mundo.",
    "A vida é geografia, explore.",
    "Acredite na geografia.",
    "Seja o explorador do seu mundo.",
    "A química transforma a matéria.",
    "A vida é química, transforme-se.",
    "Acredite na química.",
    "Seja a transformação.",
    "A física explica o universo.",
    "A vida é física, entenda as leis.",
    "Acredite na física.",
    "Seja a energia.",
    "A biologia estuda a vida.",
    "A vida é biologia, viva plenamente.",
    "Acredite na biologia.",
    "Seja a vida.",
    "A astronomia nos mostra as estrelas.",
    "A vida é astronomia, alcance as estrelas.",
    "Acredite na astronomia.",
    "Seja a sua própria estrela guia.",
];
